export const DiseaseLabels = [
    "Apple-->Apple_scab",
    "Apple-->Black_rot",
    "Apple-->Cedar_apple_rust",
    "Apple-->healthy",
    "Blueberry-->healthy",
    "Cherry_(including_sour)-->Powdery_mildew",
    "Cherry_(including_sour)-->healthy",
    "Corn_(maize)-->Cercospora_leaf_spot Gray_leaf_spot",
    "Corn_(maize)-->Common_rust_",
    "Corn_(maize)-->Northern_Leaf_Blight",
    "Corn_(maize)-->healthy",
    "Grape-->Black_rot",
    "Grape--> Esca_(Black_Measles",
    "Grape--> Isariopsis_Leaf_Spot",
    "Grape-->healthy",
    "Orange-->Haunglongbing_(Citrus_greening)",
    "Peach-->Bacterial_spot",
    "Peach-->healthy",
    "Pepper,_bell-->Bacterial_spot",
    "Pepper,_bell-->healthy",
    "Potato-->Early_blight",
    "Potato-->Late_blight",
    "Potato-->healthy",
    "Raspberry-->healthy",
    "Soybean-->healthy",
    "Squash-->Powdery_mildew",
    "Strawberry-->Leaf_scorch",
    "Strawberry-->healthy",
    "Tomato-->Bacterial_spot",
    "Tomato-->Early_blight",
    "Tomato-->Late_blight",
    "Tomato-->Leaf_Mold",
    "Tomato-->Septoria_leaf_spot",
    "Tomato-->Spider_mites Two-spotted_spider_mite",
    "Tomato-->Target_Spot",
    "Tomato-->Tomato_Yellow_Leaf_Curl_Virus",
    "Tomato-->Tomato_mosaic_virus",
    "Tomato-->healthy"
]

export const stateList = {
    'Andaman and Nicobar Islands': ['NICOBARS',
        'NORTH AND MIDDLE ANDAMAN',
        'SOUTH ANDAMANS'],
    'Andhra Pradesh': ['ANANTAPUR',
        'CHITTOOR',
        'EAST GODAVARI',
        'GUNTUR',
        'KADAPA',
        'KRISHNA',
        'KURNOOL',
        'PRAKASAM',
        'SPSR NELLORE',
        'SRIKAKULAM',
        'VISAKHAPATANAM',
        'VIZIANAGARAM',
        'WEST GODAVARI'],
    'Arunachal Pradesh': ['ANJAW',
        'CHANGLANG',
        'DIBANG VALLEY',
        'EAST KAMENG',
        'EAST SIANG',
        'KURUNG KUMEY',
        'LOHIT',
        'LONGDING',
        'LOWER DIBANG VALLEY',
        'LOWER SUBANSIRI',
        'NAMSAI',
        'PAPUM PARE',
        'TAWANG',
        'TIRAP',
        'UPPER SIANG',
        'UPPER SUBANSIRI',
        'WEST KAMENG',
        'WEST SIANG'],
    'Assam': ['BAKSA',
        'BARPETA',
        'BONGAIGAON',
        'CACHAR',
        'CHIRANG',
        'DARRANG',
        'DHEMAJI',
        'DHUBRI',
        'DIBRUGARH',
        'DIMA HASAO',
        'GOALPARA',
        'GOLAGHAT',
        'HAILAKANDI',
        'JORHAT',
        'KAMRUP',
        'KAMRUP METRO',
        'KARBI ANGLONG',
        'KARIMGANJ',
        'KOKRAJHAR',
        'LAKHIMPUR',
        'MARIGAON',
        'NAGAON',
        'NALBARI',
        'SIVASAGAR',
        'SONITPUR',
        'TINSUKIA',
        'UDALGURI'],
    'Bihar': ['ARARIA',
        'ARWAL',
        'AURANGABAD',
        'BANKA',
        'BEGUSARAI',
        'BHAGALPUR',
        'BHOJPUR',
        'BUXAR',
        'DARBHANGA',
        'GAYA',
        'GOPALGANJ',
        'JAMUI',
        'JEHANABAD',
        'KAIMUR (BHABUA)',
        'KATIHAR',
        'KHAGARIA',
        'KISHANGANJ',
        'LAKHISARAI',
        'MADHEPURA',
        'MADHUBANI',
        'MUNGER',
        'MUZAFFARPUR',
        'NALANDA',
        'NAWADA',
        'PASHCHIM CHAMPARAN',
        'PATNA',
        'PURBI CHAMPARAN',
        'PURNIA',
        'ROHTAS',
        'SAHARSA',
        'SAMASTIPUR',
        'SARAN',
        'SHEIKHPURA',
        'SHEOHAR',
        'SITAMARHI',
        'SIWAN',
        'SUPAUL',
        'VAISHALI'],
    'Chandigarh': ['CHANDIGARH'],
    'Chhattisgarh': ['BALOD',
        'BALODA BAZAR',
        'BALRAMPUR',
        'BASTAR',
        'BEMETARA',
        'BIJAPUR',
        'BILASPUR',
        'DANTEWADA',
        'DHAMTARI',
        'DURG',
        'GARIYABAND',
        'JANJGIR-CHAMPA',
        'JASHPUR',
        'KABIRDHAM',
        'KANKER',
        'KONDAGAON',
        'KORBA',
        'KOREA',
        'MAHASAMUND',
        'MUNGELI',
        'NARAYANPUR',
        'RAIGARH',
        'RAIPUR',
        'RAJNANDGAON',
        'SUKMA',
        'SURAJPUR',
        'SURGUJA'],
    'Dadra and Nagar Haveli': ['DADRA AND NAGAR HAVELI'],
    'Goa': ['NORTH GOA', 'SOUTH GOA'],
    'Gujarat': ['AHMADABAD',
        'AMRELI',
        'ANAND',
        'BANAS KANTHA',
        'BHARUCH',
        'BHAVNAGAR',
        'DANG',
        'DOHAD',
        'GANDHINAGAR',
        'JAMNAGAR',
        'JUNAGADH',
        'KACHCHH',
        'KHEDA',
        'MAHESANA',
        'NARMADA',
        'NAVSARI',
        'PANCH MAHALS',
        'PATAN',
        'PORBANDAR',
        'RAJKOT',
        'SABAR KANTHA',
        'SURAT',
        'SURENDRANAGAR',
        'TAPI',
        'VADODARA',
        'VALSAD'],
    'Haryana': ['AMBALA',
        'BHIWANI',
        'FARIDABAD',
        'FATEHABAD',
        'GURGAON',
        'HISAR',
        'JHAJJAR',
        'JIND',
        'KAITHAL',
        'KARNAL',
        'KURUKSHETRA',
        'MAHENDRAGARH',
        'MEWAT',
        'PALWAL',
        'PANCHKULA',
        'PANIPAT',
        'REWARI',
        'ROHTAK',
        'SIRSA',
        'SONIPAT',
        'YAMUNANAGAR'],
    'Himachal Pradesh': ['BILASPUR',
        'CHAMBA',
        'HAMIRPUR',
        'KANGRA',
        'KINNAUR',
        'KULLU',
        'LAHUL AND SPITI',
        'MANDI',
        'SHIMLA',
        'SIRMAUR',
        'SOLAN',
        'UNA'],
    'Jammu and Kashmir ': ['ANANTNAG',
        'BADGAM',
        'BANDIPORA',
        'BARAMULLA',
        'DODA',
        'GANDERBAL',
        'JAMMU',
        'KARGIL',
        'KATHUA',
        'KISHTWAR',
        'KULGAM',
        'KUPWARA',
        'LEH LADAKH',
        'POONCH',
        'PULWAMA',
        'RAJAURI',
        'RAMBAN',
        'REASI',
        'SAMBA',
        'SHOPIAN',
        'SRINAGAR',
        'UDHAMPUR'],
    'Jharkhand': ['BOKARO',
        'CHATRA',
        'DEOGHAR',
        'DHANBAD',
        'DUMKA',
        'EAST SINGHBUM',
        'GARHWA',
        'GIRIDIH',
        'GODDA',
        'GUMLA',
        'HAZARIBAGH',
        'JAMTARA',
        'KHUNTI',
        'KODERMA',
        'LATEHAR',
        'LOHARDAGA',
        'PAKUR',
        'PALAMU',
        'RAMGARH',
        'RANCHI',
        'SAHEBGANJ',
        'SARAIKELA KHARSAWAN',
        'SIMDEGA',
        'WEST SINGHBHUM'],
    'Karnataka': ['BAGALKOT',
        'BANGALORE RURAL',
        'BELGAUM',
        'BELLARY',
        'BENGALURU URBAN',
        'BIDAR',
        'BIJAPUR',
        'CHAMARAJANAGAR',
        'CHIKBALLAPUR',
        'CHIKMAGALUR',
        'CHITRADURGA',
        'DAKSHIN KANNAD',
        'DAVANGERE',
        'DHARWAD',
        'GADAG',
        'GULBARGA',
        'HASSAN',
        'HAVERI',
        'KODAGU',
        'KOLAR',
        'KOPPAL',
        'MANDYA',
        'MYSORE',
        'RAICHUR',
        'RAMANAGARA',
        'SHIMOGA',
        'TUMKUR',
        'UDUPI',
        'UTTAR KANNAD',
        'YADGIR'],
    'Kerala': ['ALAPPUZHA',
        'ERNAKULAM',
        'IDUKKI',
        'KANNUR',
        'KASARAGOD',
        'KOLLAM',
        'KOTTAYAM',
        'KOZHIKODE',
        'MALAPPURAM',
        'PALAKKAD',
        'PATHANAMTHITTA',
        'THIRUVANANTHAPURAM',
        'THRISSUR',
        'WAYANAD'],
    'Madhya Pradesh': ['AGAR MALWA',
        'ALIRAJPUR',
        'ANUPPUR',
        'ASHOKNAGAR',
        'BALAGHAT',
        'BARWANI',
        'BETUL',
        'BHIND',
        'BHOPAL',
        'BURHANPUR',
        'CHHATARPUR',
        'CHHINDWARA',
        'DAMOH',
        'DATIA',
        'DEWAS',
        'DHAR',
        'DINDORI',
        'GUNA',
        'GWALIOR',
        'HARDA',
        'HOSHANGABAD',
        'INDORE',
        'JABALPUR',
        'JHABUA',
        'KATNI',
        'KHANDWA',
        'KHARGONE',
        'MANDLA',
        'MANDSAUR',
        'MORENA',
        'NARSINGHPUR',
        'NEEMUCH',
        'PANNA',
        'RAISEN',
        'RAJGARH',
        'RATLAM',
        'REWA',
        'SAGAR',
        'SATNA',
        'SEHORE',
        'SEONI',
        'SHAHDOL',
        'SHAJAPUR',
        'SHEOPUR',
        'SHIVPURI',
        'SIDHI',
        'SINGRAULI',
        'TIKAMGARH',
        'UJJAIN',
        'UMARIA',
        'VIDISHA'],
    'Maharashtra': ['AHMEDNAGAR',
        'AKOLA',
        'AMRAVATI',
        'AURANGABAD',
        'BEED',
        'BHANDARA',
        'BULDHANA',
        'CHANDRAPUR',
        'DHULE',
        'GADCHIROLI',
        'GONDIA',
        'HINGOLI',
        'JALGAON',
        'JALNA',
        'KOLHAPUR',
        'LATUR',
        'MUMBAI',
        'NAGPUR',
        'NANDED',
        'NANDURBAR',
        'NASHIK',
        'OSMANABAD',
        'PALGHAR',
        'PARBHANI',
        'PUNE',
        'RAIGAD',
        'RATNAGIRI',
        'SANGLI',
        'SATARA',
        'SINDHUDURG',
        'SOLAPUR',
        'THANE',
        'WARDHA',
        'WASHIM',
        'YAVATMAL'],
    'Manipur': ['BISHNUPUR',
        'CHANDEL',
        'CHURACHANDPUR',
        'IMPHAL EAST',
        'IMPHAL WEST',
        'SENAPATI',
        'TAMENGLONG',
        'THOUBAL',
        'UKHRUL'],
    'Meghalaya': ['EAST GARO HILLS',
        'EAST JAINTIA HILLS',
        'EAST KHASI HILLS',
        'NORTH GARO HILLS',
        'RI BHOI',
        'SOUTH GARO HILLS',
        'SOUTH WEST GARO HILLS',
        'SOUTH WEST KHASI HILLS',
        'WEST GARO HILLS',
        'WEST JAINTIA HILLS',
        'WEST KHASI HILLS'],
    'Mizoram': ['AIZAWL',
        'CHAMPHAI',
        'KOLASIB',
        'LAWNGTLAI',
        'LUNGLEI',
        'MAMIT',
        'SAIHA',
        'SERCHHIP'],
    'Nagaland': ['DIMAPUR',
        'KIPHIRE',
        'KOHIMA',
        'LONGLENG',
        'MOKOKCHUNG',
        'MON',
        'PEREN',
        'PHEK',
        'TUENSANG',
        'WOKHA',
        'ZUNHEBOTO'],
    'Odisha': ['ANUGUL',
        'BALANGIR',
        'BALESHWAR',
        'BARGARH',
        'BHADRAK',
        'BOUDH',
        'CUTTACK',
        'DEOGARH',
        'DHENKANAL',
        'GAJAPATI',
        'GANJAM',
        'JAGATSINGHAPUR',
        'JAJAPUR',
        'JHARSUGUDA',
        'KALAHANDI',
        'KANDHAMAL',
        'KENDRAPARA',
        'KENDUJHAR',
        'KHORDHA',
        'KORAPUT',
        'MALKANGIRI',
        'MAYURBHANJ',
        'NABARANGPUR',
        'NAYAGARH',
        'NUAPADA',
        'PURI',
        'RAYAGADA',
        'SAMBALPUR',
        'SONEPUR',
        'SUNDARGARH'],
    'Puducherry': ['KARAIKAL', 'MAHE', 'PONDICHERRY', 'YANAM'],
    'Punjab': ['AMRITSAR',
        'BARNALA',
        'BATHINDA',
        'FARIDKOT',
        'FATEHGARH SAHIB',
        'FAZILKA',
        'FIROZEPUR',
        'GURDASPUR',
        'HOSHIARPUR',
        'JALANDHAR',
        'KAPURTHALA',
        'LUDHIANA',
        'MANSA',
        'MOGA',
        'MUKTSAR',
        'NAWANSHAHR',
        'PATHANKOT',
        'PATIALA',
        'RUPNAGAR',
        'S.A.S NAGAR',
        'SANGRUR',
        'TARN TARAN'],
    'Rajasthan': ['AJMER',
        'ALWAR',
        'BANSWARA',
        'BARAN',
        'BARMER',
        'BHARATPUR',
        'BHILWARA',
        'BIKANER',
        'BUNDI',
        'CHITTORGARH',
        'CHURU',
        'DAUSA',
        'DHOLPUR',
        'DUNGARPUR',
        'GANGANAGAR',
        'HANUMANGARH',
        'JAIPUR',
        'JAISALMER',
        'JALORE',
        'JHALAWAR',
        'JHUNJHUNU',
        'JODHPUR',
        'KARAULI',
        'KOTA',
        'NAGAUR',
        'PALI',
        'PRATAPGARH',
        'RAJSAMAND',
        'SAWAI MADHOPUR',
        'SIKAR',
        'SIROHI',
        'TONK',
        'UDAIPUR'],
    'Sikkim': ['EAST DISTRICT',
        'NORTH DISTRICT',
        'SOUTH DISTRICT',
        'WEST DISTRICT'],
    'Tamil Nadu': ['ARIYALUR',
        'COIMBATORE',
        'CUDDALORE',
        'DHARMAPURI',
        'DINDIGUL',
        'ERODE',
        'KANCHIPURAM',
        'KANNIYAKUMARI',
        'KARUR',
        'KRISHNAGIRI',
        'MADURAI',
        'NAGAPATTINAM',
        'NAMAKKAL',
        'PERAMBALUR',
        'PUDUKKOTTAI',
        'RAMANATHAPURAM',
        'SALEM',
        'SIVAGANGA',
        'THANJAVUR',
        'THE NILGIRIS',
        'THENI',
        'THIRUVALLUR',
        'THIRUVARUR',
        'TIRUCHIRAPPALLI',
        'TIRUNELVELI',
        'TIRUPPUR',
        'TIRUVANNAMALAI',
        'TUTICORIN',
        'VELLORE',
        'VILLUPURAM',
        'VIRUDHUNAGAR'],
    'Telangana ': ['ADILABAD',
        'HYDERABAD',
        'KARIMNAGAR',
        'KHAMMAM',
        'MAHBUBNAGAR',
        'MEDAK',
        'NALGONDA',
        'NIZAMABAD',
        'RANGAREDDI',
        'WARANGAL'],
    'Tripura': ['DHALAI',
        'GOMATI',
        'KHOWAI',
        'NORTH TRIPURA',
        'SEPAHIJALA',
        'SOUTH TRIPURA',
        'UNAKOTI',
        'WEST TRIPURA'],
    'Uttar Pradesh': ['AGRA',
        'ALIGARH',
        'ALLAHABAD',
        'AMBEDKAR NAGAR',
        'AMETHI',
        'AMROHA',
        'AURAIYA',
        'AZAMGARH',
        'BAGHPAT',
        'BAHRAICH',
        'BALLIA',
        'BALRAMPUR',
        'BANDA',
        'BARABANKI',
        'BAREILLY',
        'BASTI',
        'BIJNOR',
        'BUDAUN',
        'BULANDSHAHR',
        'CHANDAULI',
        'CHITRAKOOT',
        'DEORIA',
        'ETAH',
        'ETAWAH',
        'FAIZABAD',
        'FARRUKHABAD',
        'FATEHPUR',
        'FIROZABAD',
        'GAUTAM BUDDHA NAGAR',
        'GHAZIABAD',
        'GHAZIPUR',
        'GONDA',
        'GORAKHPUR',
        'HAMIRPUR',
        'HAPUR',
        'HARDOI',
        'HATHRAS',
        'JALAUN',
        'JAUNPUR',
        'JHANSI',
        'KANNAUJ',
        'KANPUR DEHAT',
        'KANPUR NAGAR',
        'KASGANJ',
        'KAUSHAMBI',
        'KHERI',
        'KUSHI NAGAR',
        'LALITPUR',
        'LUCKNOW',
        'MAHARAJGANJ',
        'MAHOBA',
        'MAINPURI',
        'MATHURA',
        'MAU',
        'MEERUT',
        'MIRZAPUR',
        'MORADABAD',
        'MUZAFFARNAGAR',
        'PILIBHIT',
        'PRATAPGARH',
        'RAE BARELI',
        'RAMPUR',
        'SAHARANPUR',
        'SAMBHAL',
        'SANT KABEER NAGAR',
        'SANT RAVIDAS NAGAR',
        'SHAHJAHANPUR',
        'SHAMLI',
        'SHRAVASTI',
        'SIDDHARTH NAGAR',
        'SITAPUR',
        'SONBHADRA',
        'SULTANPUR',
        'UNNAO',
        'VARANASI'],
    'Uttarakhand': ['ALMORA',
        'BAGESHWAR',
        'CHAMOLI',
        'CHAMPAWAT',
        'DEHRADUN',
        'HARIDWAR',
        'NAINITAL',
        'PAURI GARHWAL',
        'PITHORAGARH',
        'RUDRA PRAYAG',
        'TEHRI GARHWAL',
        'UDAM SINGH NAGAR',
        'UTTAR KASHI'],
    'West Bengal': ['24 PARAGANAS NORTH',
        '24 PARAGANAS SOUTH',
        'BANKURA',
        'BARDHAMAN',
        'BIRBHUM',
        'COOCHBEHAR',
        'DARJEELING',
        'DINAJPUR DAKSHIN',
        'DINAJPUR UTTAR',
        'HOOGHLY',
        'HOWRAH',
        'JALPAIGURI',
        'MALDAH',
        'MEDINIPUR EAST',
        'MEDINIPUR WEST',
        'MURSHIDABAD',
        'NADIA',
        'PURULIA']
}
export const crops = ['Apple', 'Arcanut (Processed)', 'Arecanut', 'Arhar/Tur',
       'Ash Gourd', 'Atcanut (Raw)', 'Bajra', 'Banana', 'Barley', 'Bean',
       'Beans & Mutter(Vegetable)', 'Beet Root', 'Ber', 'Bhindi',
       'Bitter Gourd', 'Black pepper', 'Blackgram', 'Bottle Gourd',
       'Brinjal', 'Cabbage', 'Cardamom', 'Carrot', 'Cashewnut',
       'Cashewnut Processed', 'Cashewnut Raw', 'Castor seed',
       'Cauliflower', 'Citrus Fruit', 'Coconut ', 'Coffee', 'Colocosia',
       'Cond-spcs other', 'Coriander', 'Cotton(lint)', 'Cowpea(Lobia)',
       'Cucumber', 'Drum Stick', 'Dry chillies', 'Dry ginger', 'Garlic',
       'Ginger', 'Gram', 'Grapes', 'Groundnut', 'Guar seed', 'Horse-gram',
       'Jack Fruit', 'Jobster', 'Jowar', 'Jute', 'Jute & mesta', 'Kapas',
       'Khesari', 'Korra', 'Lab-Lab', 'Lemon', 'Lentil', 'Linseed',
       'Litchi', 'Maize', 'Mango', 'Masoor', 'Mesta', 'Moong(Green Gram)',
       'Moth', 'Niger seed', 'Oilseeds total', 'Onion', 'Orange',
       'Other  Rabi pulses', 'Other Cereals & Millets',
       'Other Citrus Fruit', 'Other Dry Fruit', 'Other Fresh Fruits',
       'Other Kharif pulses', 'Other Vegetables', 'Paddy', 'Papaya',
       'Peach', 'Pear', 'Peas  (vegetable)', 'Peas & beans (Pulses)',
       'Perilla', 'Pineapple', 'Plums', 'Pome Fruit', 'Pome Granet',
       'Potato', 'Pulses total', 'Pump Kin', 'Ragi', 'Rajmash Kholar',
       'Rapeseed &Mustard', 'Redish', 'Ribed Guard', 'Rice',
       'Ricebean (nagadal)', 'Rubber', 'Safflower', 'Samai', 'Sannhamp',
       'Sapota', 'Sesamum', 'Small millets', 'Snak Guard', 'Soyabean',
       'Sugarcane', 'Sunflower', 'Sweet potato', 'Tapioca', 'Tea',
       'Tobacco', 'Tomato', 'Total foodgrain', 'Turmeric', 'Turnip',
       'Urad', 'Varagu', 'Water Melon', 'Wheat', 'Yam', 'other fibres',
       'other misc. pulses', 'other oilseeds']